name: Deploy on Laptop

on:
  workflow_run:
    workflows: ["Build Portfolio"]
    types:
      - completed

permissions:
  actions: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success'}}

    runs-on: [self-hosted, laptop]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: portfolio-dist
          run-id: ${{ github.event.workflow_run.id }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: /tmp/portfolio-dist

      - name: Deploy
        run: |
          sudo rm -rf /var/www/portfolio
          sudo mkdir -p /var/www/portfolio
          sudo cp -r /tmp/portfolio-dist/. /var/www/portfolio

